sudo: required
services:
  - docker

before_install:
  - docker build  -t javedsmy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true javedsmy/docker-react npm run test -- --coverage


deploy:
   provider: elasticbeanstalk
   region: "us-west-2"
   app: "docker-reacr"
   env: "Dockerreacr-env"
   bucket_name: "elasticbeanstalk-us-west-2-452653052153"
   bucket_path: "docker-reacr"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: "$AWS_SECRET_KEY"